version: "3.9"
services:
  first_service:
    build: ./first_service/
    container_name: first_service
    ports:
      - "8001:80"
    command: ["/start-reload.sh"]
    volumes:
      - ./first_service/v1:/app/app
  second_service:
    build: ./second_service/
    container_name: second_service
    ports:
      - "8002:80"
    command: ["/start-reload.sh"]
    volumes:
      - ./second_service/v1:/app/app
  third_service:
    build: ./third_service/
    container_name: third_service
    ports:
      - "8003:80"
    command: ["/start-reload.sh"]
    volumes:
      - ./third_service/v1:/app/app
  fourth_service:
    build: ./fourth_service/
    container_name: fourth_service
    ports:
      - "8004:8080"
      - "50051:50051"
    volumes:
      - ./fourth_service/protos:/usr/src/app/protos
      - ./fourth_service/server.js:/usr/src/app/server.js
  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - "8000:80"
    environment:
      - NGINX_PORT=80
      - SERVER_ADDRESS=localhost
      - SERVER_PORT=8000
    depends_on:
      - first_service
      - second_service
      - third_service
      - fourth_service



networks:
  default:
      ipam:
          driver: default
          config:
              - subnet: 172.24.0.1/16